# syntax=docker/dockerfile:1

FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY .docker-build/iuna-node-linux-x86_64 /usr/local/bin/iuna
RUN chmod +x /usr/local/bin/iuna
COPY README.md /usr/share/doc/iuna/README.md
COPY LICENSE /usr/share/doc/iuna/LICENSE

WORKDIR /data

EXPOSE 18661 9444

ENTRYPOINT ["iuna"]
CMD ["--data-dir", "/data", "--http", "0.0.0.0:18661", "--p2p", "0.0.0.0:9444", "--p2p-announce", "142.132.164.59:9444"]
