apiVersion: v1
kind: Namespace
metadata:
  name: iuna
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-db-pvc
  namespace: iuna
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  namespace: iuna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iuna-www
  template:
    metadata:
      labels:
        app: iuna-www
    spec:
      containers:
        - name: iuna-www
          image: ${IUNA_WWW_IMAGE}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iuna-www
  namespace: iuna
spec:
  selector:
    app: iuna-www
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iuna-tls-ingress
  namespace: iuna
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: getiuna.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iuna-www
                port:
                  number: 80
  tls:
    - secretName: iuna-tls
      hosts:
        - getiuna.org
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: iuna-redirect-to-getiuna
  namespace: iuna
spec:
  redirectRegex:
    regex: "^https?://iuna\\.jhx\\.app(?:/(.*))?$"
    replacement: "https://getiuna.org/$1"
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: iuna-redirect
  namespace: iuna
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`iuna.jhx.app`)
      kind: Rule
      middlewares:
        - name: iuna-redirect-to-getiuna
      services:
        - name: iuna-www
          port: 80
  tls:
    secretName: iuna-redirect-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iuna-admin-tls-ingress
  namespace: iuna
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,iuna-iuna-admin-ip-allowlist@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: admin.iuna.jhx.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iuna-management
                port:
                  number: 18661
  tls:
    - secretName: iuna-admin-tls
      hosts:
        - admin.iuna.jhx.app
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: iuna-admin-ip-allowlist
  namespace: iuna
spec:
  ipAllowList:
    sourceRange:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: iuna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iuna-node
  template:
    metadata:
      labels:
        app: iuna-node
    spec:
      containers:
        - name: iuna-node
          image: ${IUNA_NODE_IMAGE}
          imagePullPolicy: IfNotPresent
          ports:
            - name: management
              containerPort: 18661
            - name: p2p
              containerPort: 9444
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: local-path-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: iuna-management
  namespace: iuna
spec:
  selector:
    app: iuna-node
  ports:
    - name: management
      port: 18661
      targetPort: 18661
---
apiVersion: v1
kind: Service
metadata:
  name: iuna
  namespace: iuna
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: iuna-node
  ports:
    - name: p2p
      port: 9444
      targetPort: 9444
